### ISSUE TITLE
Docs - improvements

### ISSUE THREAD

**Issue by richburdon** [dxos/web#14]
- Structure
  - Landing Page (Gatsby)
    - [x] Live deploy from `production` branch -> https://dxos.org
    - [x] QA deploy from `main` branch -> https://qa-dxos-web.netlify.app
    - [x] Setup qa.dxos.org domain
  - Main Docs Site (Docusaurus)
    - [x] Live deploy from `production` branch -> https://dxos-docs.netlify.app
    - [x] QA deploy from `main` branch -> https://qa-dxos-docs.netlify.app
    - [x] Setup qa.dxos.org/docs routing
    - [x] Publish dxos-api.json file from protocols on npm
  - Demos Site (esbuild-server book w/ same look & feel as docs)
    - [x] Move demos from `protocols` repo to `demos` repo
    - [x] Live deploy from `production` branch -> https://dxos-demos.netlify.app
    - [x] QA deploy from `main` branch -> https://qa-dxos-demos.netlify.app
    - [x] Setup qa.dxos.org/demos routing
  - Github Docs
    - [ ] #23
    - [x] Rename `dot` repo to `dxns`?
- Content
  - Landing Page
    - [ ] Review landing page content
  - Main Docs Site
    - [ ] Remove content from root page which is only visible during development
    - [ ] #24
    - [ ] #27
    - [ ] #28
    - [x] #29
    - [ ] Expand API reference & fill out JSDocs
    - [x] #37
    - [ ] Move all user-facing docs to single location (archive folder in `web` repo)
    - [ ] Move tutorial app out of protocols repo
    - [ ] Document documentation structure and how to update in wiki
  - Showcase Demos
    - [x] #25
    - [ ] #31
    - [ ] #32
    - [ ] #33
    - [ ] #34
    - [ ] #30
  - Github Docs
    - [ ] #26
    - [ ] CLI README
    - [ ] KUBE REAME
    - [ ] DXNS README
    - [ ] Braneframe README
    - [ ] Console README
- General Review
  - [ ] make sure all links work
  - [ ] make sure code works as documented
  - [ ] archive and migrate old repos to dxos-deprecated

**Comment by okreitz** [comment]
#Best Practice Docs

- https://docs.ipfs.io/
- https://developer.sandbox.co.in/
- https://thirdweb.com/portal
- https://supabase.com/docs/
- https://docs.helium.com/
- https://developer.aleo.org/
- https://developer.paypal.com/api/rest/

**Comment by wittjosiah** [comment]
## Initial Docs Sites

- [ ] Setup CI to auto-deploy all three
  - qa version
  - live version
- [ ] landing page (gatsby)
- [ ] main docs site (docusaurus)
  - home
  - tutorial
  - dev tools (cli, kube, web ext)
  - resources (generated api references, focus on client api)
- [ ] demos/tutorials site (esbuild-server)
  - same look and feel as docs but storybooks
