### ISSUE TITLE
error: docs site crashing when adding react-client as dependency from external package.

### ISSUE THREAD

**Issue by ZarcoNontol** [dxos/web#4]
## Description

There are 2 packages to take a look:

- site: where the new website is hosted.
- sanity: package that contain minimal components for testing the site. 

The goal is to include a component that uses `react-client`.

## Successfull Example:

- git checkout `zarco/isolate-dxos-app-stable`
- initialize the project, see readme.
- go to `packages/sanity` and run `yarn build`
- go to `packages/site` and run `yarn start`
- visit: http://localhost:3000/docs/demos/react
- You will see
<img width="500" alt="Screen Shot 2021-12-23 at 01 16 54" src="https://user-images.githubusercontent.com/17819818/147187195-58017e86-5c0e-49d3-ae21-bc6cbe4e600b.png">
This is what we render:

```

export const DemoApp = () => {
  return (
    <div>
      <h2>Components</h2>
      <Simple />
      <SimpleWithState />
      <MaterialSimple />
      <MaterialWithState />
      <DXOSReactComponents />
    </div>
  );
}

```
It includes:

- standalone react component
- react component with useState
- MUI Component standalone
- MUI Component with useState
- DXOS React component with jsontreeview

## Example with Error

- git checkout `zarco/isolate-dxos-app`
- lerna bootstrap
- go to `packages/sanity` and run `yarn build`
- go to `packages/site` and run `yarn start`
- visit: http://localhost:3000/docs/demos/react
- The pages crashes with the following error:
<img width="1077" alt="Screen Shot 2021-12-23 at 01 30 40" src="https://user-images.githubusercontent.com/17819818/147188223-6d54f23c-81f1-43ea-a407-6f8bbebb7cd7.png">

Once you get the error you need to clean everything and remove the dependency to make it work correctly.
The expected result would be to print out the current client object into a JSON Tree view.

```
const Main = () => {
  const client = useClient();
  return (
    <JsonTreeView data={client} />
  );
}

export const SimpleWithClient = () => {
  const [count, setCount] = useState(1);

  return (
    <ClientProvider>
      <Main />
    </ClientProvider>
  );
};

export const SimpleWithRemoteClient = ({ clientProvider }: { clientProvider: any }) => {
  const RemoteClientProvider = clientProvider;
  return (
    <RemoteClientProvider>
      <Main />
    </RemoteClientProvider>
  );
};

```

Related files:

- `packages/sanity/src/index.tsx` all the components listed hee
- `packages/site/src/demos/DemoApp.js` demo app that gets imported in a MDX file
- MDX File: `packages/site/docs/9-demos/react.mdx`

**Comment by rzadp** [comment]
Issue reproduced on my machine.

**Comment by rzadp** [comment]
@ZarcoNontol Please take a look at `rzadp/isolate-dxos-app`

**Comment by ZarcoNontol** [comment]
Working correctly! Closing this.
